site_name: Brown Dust II Overview
theme:
  name: material
  palette:
    scheme: slate  # Dark mode
    primary: indigo
    accent: cyan
    
nav:
    - Home: index.md
    - 'Content Packs':
        - 'Mirror Wars': content-packs/mirror-wars.md
        - 'Evil Castle': content-packs/evil-castle.md
        - 'Path of Adventure': content-packs/path-of-adventure.md
        - 'Last Night': content-packs/last-night.md
        - 'Glupy Diner': content-packs/glupy-diner.md
        - 'Golden Colosseum': content-packs/golden-colosseum.md
        - 'Fantasia Square': content-packs/fantasia-square.md
    - 'Characters info':
        - 'Potential Liberation': character-info/potential-liberation.md
repo_name: BotAn14XD/BD2-Overview
repo_url: https://github.com/BotAn14XD/BD2-Overview
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - glightbox:
      skip_classes:
        - icon
  - git-revision-date-localized:
      type: date
      timezone: UTC
  - macros
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  gold: '![Gold](../assets/images/icons/Gold.png){ .icon} Gold'
  gold_pic: '![Gold](../assets/images/icons/Gold.png){ .icon}'
  ancient_crystals: '![Ancient Crystals](../assets/images/icons/Ancient_Crystal.png){ .icon } Ancient Crystals'
  ancient_crystals_pic: '![Ancient Crystals](../assets/images/icons/Ancient_Crystal.png){ .icon }'
  draw_tickets: '![Draw Tickets](../assets/images/icons/Draw_Tickets.png){ .icon } Draw Tickets'
  draw_tickets_pic: '![Draw Tickets](../assets/images/icons/Draw_Tickets.png){ .icon }'
  cooked_rice: '![Cooked Rice](../assets/images/icons/Cooked_Rice.png){ .icon } Cooked Rice'
  cooked_rice_pic: '![Cooked Rice](../assets/images/icons/Cooked_Rice.png){ .icon }'
  cocktails: '![Blood Cocktails](../assets/images/icons/Blood_Cocktails.png){ .icon } Blood Cocktails'
  cocktails_pic: '![Blood Cocktails](../assets/images/icons/Blood_Cocktails.png){ .icon }'
  dias: '![Dias](../assets/images/icons/Dias.png){ .icon } Dias'
  dias_pic: '![Dias](../assets/images/icons/Dias.png){ .icon }'
  pvp_medals: '![Medals of the Fighting Spirit](../assets/images/icons/Medals of the Fighting Spirit.png){ .icon } Medals of the Fighting Spirit'
  pvp_medals_pic: '![Medals of the Fighting Spirit](../assets/images/icons/Medals of the Fighting Spirit.png){ .icon }'